# Generated by Django 5.2 on 2025-05-10 10:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller')], max_length=10)),
                ('activation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=10)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table_comment': 'Role assigned to a user',
                'ordering': ['-activation_date', 'type'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.'), django.core.validators.RegexValidator(message='Enter a valid email address.', regex='^.+@.+\\..+$')])),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=10)),
                ('legal_type', models.CharField(choices=[('PRIVATE', 'Private'), ('SHOPKEEPER', 'Shopkeeper')], max_length=10)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table_comment': 'Registered user of the application',
                'ordering': ['-registration_date', 'username'],
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'type': 'BUYER'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.role')),
                ('shipping_address', models.TextField()),
            ],
            options={
                'verbose_name': 'Buyer',
                'verbose_name_plural': 'Buyers',
                'db_table_comment': 'Buyer role of a user',
            },
        ),
        migrations.CreateModel(
            name='Private',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.role')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('fiscal_code', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'verbose_name': 'Private Vendor',
                'verbose_name_plural': 'Private Vendors',
                'db_table_comment': 'A private vendor',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'type': 'SELLER'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.role')),
                ('collection_address', models.TextField()),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
                'db_table_comment': 'Seller assigned to a user',
            },
        ),
        migrations.CreateModel(
            name='Shopkeeper',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.role')),
                ('business_name', models.CharField(max_length=100)),
                ('iva_number', models.CharField(max_length=11, unique=True)),
                ('headquarters_address', models.TextField()),
            ],
            options={
                'verbose_name': 'Shopkeeper',
                'verbose_name_plural': 'Shopkeepers',
                'db_table_comment': 'A shopkeeper',
                'ordering': ['business_name'],
            },
        ),
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('user', 'type')},
        ),
    ]
