# Generated by Django 5.2 on 2025-05-10 10:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_text', models.TextField()),
                ('read_status', models.BooleanField(default=False)),
                ('notification_type', models.CharField(choices=[('AUCT_WON', 'Auction Won'), ('AUCT_END', 'Auction Ending'), ('GENERIC', 'Generic Notification')], default='GENERIC', max_length=10)),
                ('notification_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table_comment': 'A user notification',
                'ordering': ['-notification_date'],
            },
        ),
    ]
