# Generated by Django 5.2 on 2025-05-10 10:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'verbose_name': 'Favorite Auction',
                'verbose_name_plural': 'Favorite Auctions',
                'db_table_comment': 'The favourite auctions of a user',
                'ordering': ['-added_on'],
                'unique_together': {('user', 'auction')},
            },
        ),
        migrations.CreateModel(
            name='RecentlyViewedAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'verbose_name': 'Recently Viewed Auction',
                'verbose_name_plural': 'Recently Viewed Auctions',
                'db_table_comment': 'The recently viewed auctions of a user',
                'ordering': ['-viewed_on'],
                'unique_together': {('user', 'auction')},
            },
        ),
    ]
