"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# These settings are common to all environments (development, production, etc.).
# Some other options are specified in local.py (for development) and production.py (for production).
# These files extend and override these categories with environment-specific configurations.

from config.env import env


# ======================================================== #
# ========================= Paths ======================== #
# ======================================================== #

import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent.parent
PROJ_DIR = BASE_DIR / 'config'
APPS_DIR = BASE_DIR / 'apps'
COMM_DIR = BASE_DIR / 'common'
DATA_DIR = BASE_DIR / 'data'
ENVS_DIR = PROJ_DIR / 'envs'

# Add the apps directoriy to Python's path. In production it will
# be necessary to add the apps directory to the path, too.
sys.path.append(str(APPS_DIR))


# ======================================================== #
# ==================== Load Environment ================== #
# ======================================================== #
# Some options are specified in local.py and produ.py      #

env.read_env(str(ENVS_DIR / '.env'))


# ======================================================== #
# ======================= Settings ======================= #
# ======================================================== #

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DJANGO_DEBUG', default=True)

# SECURITY WARNING: Specify only the allowed hosts when in production!
ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS', default=[])


# ======================================================== #
# ================= Application Settings ================= #
# ======================================================== #

DEFAULT_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

EXTERNAL_APPS = [
    'django_extensions',
    'jazzmin',
]

INTERNAL_APPS = [
    'core',
    'accounts',
    'auctions',
    'wallet',
    'inbox',
    'reviews',
    'favorites'
]

INSTALLED_APPS = \
    INTERNAL_APPS + EXTERNAL_APPS + DEFAULT_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            COMM_DIR / 'templates',
            COMM_DIR / 'templates/base',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ======================================================== #
# ============= External Application Settings ============ #
# ======================================================== #

JAZZMIN_SETTINGS = {
    'site_header': 'Graboid Admin',
    'site_brand': 'Graboid Admin Page',
    'site_logo': 'base/images/favicon/favicon.ico',
    'copyright': 'graba',
}


# ======================================================== #
# ================== Password Validators ================= #
# ======================================================== #

# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ======================================================== #
# ==================== Custom Loggers ==================== #
# ======================================================== #

# https://docs.djangoproject.com/en/5.2/topics/logging/#loggers

from scripts.logger import CustomFormatter

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'colored_console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
            'formatter': 'color',
        },
    },
    'formatters': {
        'color': {
            '()': CustomFormatter,
        },
    },
    'loggers': {
        'django': {
            'handlers': ['colored_console'],
            'level': 'INFO',
            'propagate': True,
        },
        'custom': {
            'handlers': ['colored_console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}


# ======================================================== #
# ======================= Database ======================= #
# ======================================================== #

# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if env('DATABASE_URL', default=None) is not None:
    
    # Enable database config through environment
    DATABASES = {'default': env.db()}

else:
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': DATA_DIR / 'db.dev.sqlite3',
            'TEST': {
                'NAME': DATA_DIR / 'db.test.sqlite3',
            }
        }
    }


# ======================================================== #
# ================= Internationalization ================= #
# ======================================================== #

# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ======================================================== #
# ======== Static files (CSS, JavaScript, Images) ======== #
# ======================================================== #
# Some options are specified in local.py and produ.py      #

# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = DATA_DIR / 'staticfiles'

STATICFILES_DIRS = [
    # Base Static Folder Registration
    COMM_DIR / 'static',

    # Base Static Folder Aliases Registration
    ('static_base', COMM_DIR / 'static/base'),
    
    # External Static Folder Aliases Registration
    #   e.g. ('static_<app_name>', APPS_DIR / '<app_name>/static/<app_name>'),

    # Internal Static Folder Aliases Registration
    #   is done automatically

] + [(f'static_{appname}', APPS_DIR / f'{appname}/static/{appname}') for appname in INTERNAL_APPS]

MEDIA_URL = '/media/'

MEDIA_ROOT = DATA_DIR / 'mediafiles'


# ======================================================== #
# ==================== Model Settings ==================== #
# ======================================================== #

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ======================================================== #
# ==================== Authentication ==================== #
# ======================================================== #

AUTH_USER_MODEL = 'accounts.User'

LOGIN_REDIRECT_URL = '/'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]
