# Generated by Django 5.2 on 2025-05-10 10:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(blank=True, null=True)),
                ('review_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auctions.winneroffer')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table_comment': 'A review a buyer left for a seller after winning the auction',
                'ordering': ['-review_date'],
            },
        ),
    ]
